### ISSUE TITLE
Converting Filed

### ISSUE THREAD

**Issue by DenisShahbazyan** [realcoloride/YoutubeDL#2]
I'm trying to download 1080, 60 fps video. The error "Converting Filed" appears.
Here's that video: 
https://www.youtube.com/watch?v=LXb3EKWsInQ

**Comment by realcoloride** [comment]
Hello, for me it worked.
Please try again, disable your VPN or refresh the page. Also check if you have set up your tampermonkey permissions correctly.

**Comment by DenisShahbazyan** [comment]
That's weird. Didn't do anything, just tried it again and it worked.... Thanks! Nice extension!
