### ISSUE TITLE
Does it work in Android Firefox browser?

### ISSUE THREAD

**Issue by samshine1212** [realcoloride/YoutubeDL#4]
installed the extension in Android Firefox browser
The icon to download the video doesn't appear!

**Comment by realcoloride** [comment]
The extension is temporarily broken due to restrictions. https://github.com/realcoloride/YoutubeDL/issues/3#issuecomment-2365220992

**Comment by tgmb1** [comment]
Ok dev

**Comment by realcoloride** [comment]
See #3
